#!perl

use 5.010001;
use strict;
use warnings;

use App::GitUtils;
use Perinci::CmdLine::Any;

# AUTHORITY
# DATE
# DIST
# VERSION

my $p = '/App/GitUtils/'; # prefix
Perinci::CmdLine::Any->new(
    url => $p,
    subcommands => {
        'info'           => {url => "${p}info"},
        'status'         => {url => "${p}status"},
        'run-hook'       => {url => "${p}run_hook"},
        'rh'             => {url => "${p}run_hook",
                             summary => 'Alias for run-hook'},
        'post-commit'    => {url => "${p}post_commit"},
        'pre-commit'     => {url => "${p}pre_commit"},
        'clone-to-bare'  => {url => "${p}clone_to_bare"},
        'du-untracked'   => {url => "${p}calc_untracked_total_size"},
        'du-committing'  => {url => "${p}calc_committing_total_size"},
        'ls-committing-large' => {url => "${p}list_committing_large_files"},
    },
    default_subcommand => 'info',
    get_subcommand_from_arg => 2,
)->run;

# ABSTRACT:
# PODNAME:
